Add TestGeneratorOverlaysBinaryData - fails due to missing binary data support
Port of Go kustomize TestGeneratorOverlaysBinaryData. Currently fails because
kustomizer doesn't support binary files in configMapGenerator files field.
Error: "stream did not contain valid UTF-8"

Need to implement binary data handling with base64 encoding and binaryData
field in ConfigMaps instead of data field.